apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: mongo-express:latest #path can also be given
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-config #from the metadata
                key: mongo-url
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password


--- # Service (after 3 --- its treated as a new or separate file in yaml)

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app : webapp #from line no 6 of deployment
  ports:
    - protocol: TCP
      port: 8081 #port of the service
      targetPort: 8081 #port of the container
      nodePort: 30100 #port of the node
  type: NodePort